spring:
  application:
    name: Store
server:
  port: 8081   # cambia si usas gateway u otros servicios

spring:
  application:
    name: store

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # usar 'validate' o 'none' en producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

  sql:
    init:
      mode: always

# Logs (útil para debug)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuración interna (para seguridad entre microservicios)
security:
    jwt:
      secret-key: Wm5N30DT1nFqUmdjrvM4GWqw1utDrSlpdDLyDGa4kBw=
