spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # ── Auth (público) ────────────────────────────────────────────────────
        - id: auth-routes
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/register,
              /api/v1/auth/registerSecondStep,
              /api/v1/auth/resendVerificationCode,
              /api/v1/auth/login,
              /api/v1/auth/loginSecondStep,
              /api/v1/auth/forgotPassword,
<<<<<<< HEAD
              /api/v1/auth/forgotPasswordSecondStep
=======
              /api/v1/auth/forgotPasswordSecondStep,
              /api/v1/auth/deactivateAccount,
>>>>>>> 39a86a44966c35c642d5a12aa1f80ebdb32484d7

        # ── Tiendas ───────────────────────────────────────────────────────────
        - id: store-routes
          uri: http://localhost:8081
          predicates:
            - Path=/api/stores,
              /api/stores/**

        - id: product-routes
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/products,
              /api/v1/products/**,
              /api/v1/categories/**,
              /api/v1/brands/**

        # ── Alertas de stock SSE ──────────────────────────────────────────────
        - id: stock-alert-routes
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/alerts/stock/stream

        # ── Variantes ─────────────────────────────────────────────────────────
        - id: variant-routes
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/variants,
              /api/v1/variants/**

        # ── Usuarios (requiere JWT) ───────────────────────────────────────────
        - id: users-routes
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/me,
              /api/v1/users/createUser,
              /api/v1/users/update,
              /api/v1/users/{id}
          filters:
            - JwtValidationFilter

server:
  port: 8080

security:
  jwt:
    secret-key: Wm5N30DT1nFqUmdjrvM4GWqw1utDrSlpdDLyDGa4kBw=