spring:
  application:
    name: cart

  datasource:
    url: jdbc:postgresql://localhost:5432/cart
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8086}
  servlet:
    context-path: /api/v1

store:
  service:
    url: ${STORE_SERVICE_URL:http://localhost:8081/api/v1}

product:
  service:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8084/api/v1}

promotion:
  service:
    url: ${PROMOTION_SERVICE_URL:http://localhost:8091/api/v1}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secret-key: ${JWT_SECRET:Wm5N30DT1nFqUmdjrvM4GWqw1utDrSlpdDLyDGa4kBw=}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
