server:
  port: ${SERVER_PORT:8103}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: transaction

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transaction}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

mercadopago:
  access-token: ${MP_ACCESS_TOKEN:test}
  webhook-secret: ${MP_WEBHOOK_SECRET:test}
  notification-url: ${MP_NOTIFICATION_URL:http://localhost:8103}
payment:
  mock: ${PAYMENT_MOCK:true}


management:
  endpoints:
    web:
      exposure:
        include: "health,info"
