server:
  port: ${SERVER_PORT:8105}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: pos-sale-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pos_sale}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

inventory:
  service:
    base-url: ${INVENTORY_SERVICE_URL:http://localhost:8089/api/v1}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always
